import { LitElement, PropertyValues } from 'lit';
import './hausgeist-card-editor';
declare module 'three/examples/jsm/loaders/GLTFLoader.js';
export declare class HausgeistCard extends LitElement {
    hass: any;
    config: {
        area_id?: string;
        overrides?: any;
        auto?: any;
        debug?: boolean;
        notify?: boolean;
        highThreshold?: number;
        rulesJson?: string;
        areas?: Array<{
            area_id: string;
            name: string;
            enabled?: boolean;
        }>;
        weather_entity?: string;
        default_target?: number;
        default_adjacent_room_temp?: number;
        default_outside_temp?: number;
        ghost_model_url?: string;
    };
    debug: boolean;
    notify: boolean;
    highThreshold: number;
    rulesJson: string;
    static styles: import("lit").CSSResult[];
    private engine?;
    private texts;
    private ready;
    private ghost3D?;
    private lastTip;
    private ghostLoadError;
    private _currentPriority;
    private _currentAreaIndex;
    private _lastAreaEvalTimestamp;
    private _areaEvalInterval;
    private _areaResults;
    private _resolvedAreas;
    private _pendingAreaQueue;
    private _evaluationTimer;
    private _areaSensorCache;
    private _areaLastEval;
    private _areaMaxEvalInterval;
    private _tempHistory;
    private _targetHistory;
    private _humidityHighSince;
    private _windowOpenSince;
    private _doorOpenSince;
    setConfig(config: any): void;
    static getConfigElement(): Promise<HTMLElement>;
    static getStubConfig(): {
        debug: boolean;
        notify: boolean;
        highThreshold: number;
        default_target: number;
        default_adjacent_room_temp: number;
        default_outside_temp: number;
    };
    connectedCallback(): Promise<void>;
    protected willUpdate(changedProps: PropertyValues): void;
    updated(changedProps: PropertyValues): void;
    disconnectedCallback(): void;
    private _getCurrentTip;
    render(): import("lit-html").TemplateResult<1>;
    private _findSensor;
    private _getTargetTemperature;
    private _buildContext;
    private _calculateTempChangeRate;
    private _trackTargetChange;
    private _updateActiveDuration;
    private _getStatesArray;
    private _resolveDefaultTarget;
    private _refreshAreasCache;
    private _enqueueAreasForEvaluation;
    private _processEvaluationQueue;
}
